### ISSUE TITLE
leaderboard congrats page

### ISSUE THREAD

**Issue by derogative404** [UoaWDCC/passport#43]
## Description

As a user
I want to view the congrats page when I achieve a prize

## Acceptance Criteria

- [x] uses route `leaderboard-prize`
- [ ] designed as per figma

## Notes

```[tasklist]
### Tasks
- [ ] link the prizes achieved to the actual api
- [ ] merge tickets w erica and create a PR
```

**Comment by derogative404** [comment]
completed
